name: Compile and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Compile
      run: make jar
    - name: Tests
      run: cd tests && bash test.sh
    - name: Package
      run: make deb rpm 'RPMBUILD_FLAGS=--nodeps --nocheck' 'DPKG_FLAGS=-d'
    - uses: actions/upload-artifact@v2
      with:
        name: binary-packages
        path: dftres-*.noarch.rpm
    - uses: actions/upload-artifact@v2
      with:
        name: binary-packages
        path: dftres_*_all.deb
